'use client';
import { useEffect, useState } from 'react';
import { api, BookingHeader, dateTime, FACEBOOK, money, statusLabel } from '../booking-ui';
type Booking = { id:string; status:string; startAt:number; endAt:number; players:number; location:string; estimatedTotal:number; quotedTotal:number|null; expiresAt:number; paymentsReady:boolean; confirmationEmail:string };
export default function BookingStatus() {
  const [booking,setBooking]=useState<Booking|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
  async function load() { setBusy(true);setError('');try {const p=new URLSearchParams(window.location.hash.slice(1));if(!p.get('id')||!p.get('token')) throw new Error('Open the private link you received after reserving a session.');setBooking(await api<Booking>(`/api/reservations/${p.get('id')}`,{headers:{Authorization:`Bearer ${p.get('token')}`}}));}catch(e){setError((e as Error).message);}finally{setBusy(false);} }
  useEffect(()=>{void load();},[]);
  async function checkout(){setBusy(true);setError('');try{const p=new URLSearchParams(window.location.hash.slice(1));const result=await api<{url:string}>(`/api/reservations/${p.get('id')}/checkout`,{method:'POST',headers:{Authorization:`Bearer ${p.get('token')}`},body:'{}'});window.location.assign(result.url);}catch(e){setError((e as Error).message);setBusy(false);}}
  return <><BookingHeader label="Your reservation"/><main className="booking-page container"><p className="eyebrow dark-eyebrow">ONE STEP CLOSER TO COURT</p><h1>Your session.<br/><em>Your next step.</em></h1>{error&&<p className="notice notice-error" role="alert">{error}</p>}{!booking&&busy&&<p role="status">Loading your reservation…</p>}{booking&&<article className="status-card"><span className={`status-badge status-${booking.status}`}>{statusLabel[booking.status]}</span><h2>{dateTime(booking.startAt)}</h2><p>Philippine time (UTC+8) · {booking.players} player(s)</p><dl className="booking-details"><div><dt>Court</dt><dd>{booking.location}</dd></div><div><dt>{booking.quotedTotal===null?'Estimated total':'Final quote'}</dt><dd>{money(booking.quotedTotal??booking.estimatedTotal)}</dd></div><div><dt>Reference</dt><dd>{booking.id}</dd></div></dl>
    {['pending_review','awaiting_payment'].includes(booking.status)&&<><p className="notice">Your time is held until {dateTime(booking.expiresAt)}. This reservation is not confirmed. {booking.status==='pending_review'?'Coach Jeremy will review your court location and final rate.':'Your quote is ready. Verified payment is required to confirm.'}</p>{booking.paymentsReady&&booking.status==='awaiting_payment'?<button className="button button-dark" disabled={busy} onClick={checkout}>Continue to secure payment ↗</button>:<p>Online payment is not connected yet. Please message Coach Jeremy about your session.</p>}</>}
    {booking.status==='confirmed'&&<p className="notice">Your payment has been verified. {booking.confirmationEmail==='sent'?'Your confirmation email has been sent. Please check your inbox and spam folder.':'Your confirmation email is queued for delivery. Contact Coach Jeremy if it does not arrive.'}</p>}
    {['expired','cancelled'].includes(booking.status)&&<p>This reservation no longer holds a session. <a className="text-link" href="/#book">Choose another time ↗</a></p>}
    <div className="dashboard-actions"><button className="button button-outline" disabled={busy} onClick={load}>{busy?'Refreshing…':'Refresh status'}</button><button className="button button-outline" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.href);setCopied(true);}catch{setError('Copy the link from your browser address bar to save it.');}}}>{copied?'Link copied':'Copy private link'}</button><a className="text-link" href={FACEBOOK} target="_blank" rel="noopener noreferrer">Message Coach Jeremy ↗</a></div><p className="field-note">Keep this link private. Anyone with it can view this reservation.</p></article>}<a className="text-link" href="/#book">Back to session calendar ↗</a></main></>;
}
