'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { api, ApiError, BookingHeader, dateTime, money, statusLabel } from '../booking-ui';
type Slot={id:string;start_at:number;end_at:number;state:string;reservation_id:string|null;reservation_status:string|null};
type Reservation={id:string;name:string;email:string;phone:string;location:string;players:number;status:string;estimated_total:number;quoted_total:number|null;expires_at:number;start_at:number};
type Dashboard={slots:Slot[];reservations:Reservation[];emails:{id:string;recipient:string;subject:string;state:string;attempts:number}[];paymentsReady:boolean;emailReady:boolean;adminEmail:string};
const localTime=(ms:number)=>new Date(ms+8*3600000).toISOString().slice(0,16);
export default function Admin(){
 const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(''),[auth,setAuth]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[editing,setEditing]=useState<Slot|null>(null);
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[state,setState]=useState('open');
 async function load(){setError('');try{setData(await api<Dashboard>('/api/admin/dashboard'));setAuth(0);}catch(e){if(e instanceof ApiError)setAuth(e.status);setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function mutate(path:string,body:unknown,method='POST'){setBusy(true);setError('');setNotice('');try{await api(path,{method,body:JSON.stringify(body)});await load();setNotice('Changes saved.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 function reset(){setEditing(null);setStart('');setEnd('');setState('open');}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);const starts=Date.parse(`${fields.get('starts')}+08:00`),ends=Date.parse(`${fields.get('ends')}+08:00`);if(!Number.isFinite(starts)||!Number.isFinite(ends)){setError('Please enter valid start and end dates.');return;}if(await mutate(editing?`/api/admin/slots/${editing.id}`:'/api/admin/slots',{startAt:new Date(starts).toISOString(),endAt:new Date(ends).toISOString(),state},editing?'PATCH':'POST'))reset();}
 function edit(s:Slot){setEditing(s);setStart(localTime(s.start_at));setEnd(localTime(s.end_at));setState(s.state);document.getElementById('schedule-editor')?.scrollIntoView({block:'center'});}
 return <><BookingHeader label="Coach dashboard"/><main className="container admin-page"><p className="eyebrow dark-eyebrow">YOUR COURT. YOUR CALENDAR.</p><h1>Manage your<br/><em>coaching schedule.</em></h1>
 {error&&<p role="alert" className="notice notice-error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {auth===401&&<div className="status-card"><h2>Welcome back, Coach.</h2><p>Sign in with the ChatGPT account using <strong>yourvajeremyalonzo@gmail.com</strong> to manage availability and reservations.</p><a className="button button-dark" href="/signin-with-chatgpt?return_to=%2Fadmin" target="_top">Sign in with ChatGPT ↗</a></div>}
 {auth===403&&<p>This dashboard is restricted to your coaching admin account. Switch to the authorized account and refresh.</p>}
 {!data&&auth!==401&&<button className="button button-outline" onClick={load}>Refresh dashboard</button>}
 {data&&<><div className="admin-integrations"><span><i className={data.paymentsReady?'connected':''}/>Payments: {data.paymentsReady?'connected':'not connected yet'}</span><span><i className={data.emailReady?'connected':''}/>Email: {data.emailReady?'connected':'not connected yet'}</span><button className="text-link" onClick={load} disabled={busy}>Refresh ↻</button></div><p className="field-note">Signed in as {data.adminEmail}. All times are Philippine time (UTC+8). A session confirms only after verified payment. Unpaid holds expire within 24 hours.</p>
 <div className="admin-grid"><section className="status-card" id="schedule-editor"><p className="tiny-label">AVAILABILITY</p><h2>{editing?'Edit session':'Add court time'}</h2><p>Add one bookable session at a time, or block a time you’re unavailable. Each session reserves the full time range for one group.</p><form className="schedule-form" onSubmit={save}><label>Starts (Philippine time)<input type="datetime-local" name="starts" value={start} onChange={e=>setStart(e.target.value)} required step={1800}/></label><label>Ends (Philippine time)<input type="datetime-local" name="ends" value={end} onChange={e=>setEnd(e.target.value)} required step={1800}/></label><label>Availability<select value={state} onChange={e=>setState(e.target.value)}><option value="open">Open for reservations</option><option value="blocked">Blocked / unavailable</option></select></label><p className="field-note">At least 1 hour from now. Duration: 1–12 hours in 30-minute increments. Overlapping sessions cannot be saved.</p><div className="dashboard-actions"><button type="submit" className="button button-dark" disabled={busy}>{busy?'Saving…':editing?'Save session':'Add session'}</button>{editing&&<button type="button" className="button button-outline" onClick={reset}>Cancel edit</button>}</div></form></section>
 <section className="status-card"><h2>Your schedule</h2>{!data.slots.length?<p>No sessions yet. Add your first available time to show it on the client calendar.</p>:<div className="schedule-list">{data.slots.map(s=><article key={s.id}><div><strong>{dateTime(s.start_at)}</strong><p>Until {dateTime(s.end_at)}</p><span className="status-badge">{s.reservation_id?statusLabel[s.reservation_status||'']:s.state==='open'?'Open':'Blocked'}</span></div><div className="dashboard-actions">{!s.reservation_id&&s.start_at>Date.now()+3600000?<><button disabled={busy} className="text-link" onClick={()=>edit(s)}>Edit</button><button disabled={busy} className="text-link" onClick={()=>mutate(`/api/admin/slots/${s.id}`,{startAt:new Date(s.start_at).toISOString(),endAt:new Date(s.end_at).toISOString(),state:s.state==='open'?'blocked':'open'},'PATCH')}>{s.state==='open'?'Block':'Reopen'}</button></>:<small>{s.reservation_id?'Reserved times cannot be edited.':'Past / starting soon'}</small>}</div></article>)}</div>}</section></div>
 <section className="admin-reservations"><div className="section-heading"><h2>Reservations</h2><p>Review the court location, then set the total quote for the entire group.</p></div>{!data.reservations.length?<p className="status-card">New client requests will appear here.</p>:<div className="reservation-list">{data.reservations.map(r=><article className="status-card" key={r.id}><div className="reservation-title"><h3>{r.name}</h3><span className={`status-badge status-${r.status}`}>{statusLabel[r.status]}</span></div><p>{dateTime(r.start_at)} · {r.players} player(s)</p><p>{r.location}</p><p><a href={`mailto:${r.email}`}>{r.email}</a> · <a href={`tel:${r.phone}`}>{r.phone}</a></p><p>Estimate: <strong>{money(r.estimated_total)}</strong>{r.quoted_total!==null&&<> · Final quote: <strong>{money(r.quoted_total)}</strong></>}</p>{['pending_review','awaiting_payment'].includes(r.status)&&<><p className="field-note">Hold expires {dateTime(r.expires_at)}. Tell the client to refresh their private reservation link after you quote.</p><div className="dashboard-actions">{r.status==='pending_review'&&<form className="quote-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(`/api/admin/reservations/${r.id}/quote`,{totalPHP:Number(f.get('totalPHP'))});}}><label>Total quote (PHP)<input name="totalPHP" type="number" min="100" max="100000" step="0.01" defaultValue={r.estimated_total/100} required/></label><button className="button button-dark" disabled={busy}>Send quote to reservation</button></form>}<button className="button button-outline" disabled={busy} onClick={()=>{if(window.confirm('Cancel this unpaid reservation and release its time?'))void mutate(`/api/admin/reservations/${r.id}/cancel`,{});}}>Cancel pending reservation</button></div></>}<small className="reference">Reference: {r.id}</small></article>)}</div>}</section>
 <section className="status-card"><h2>Email delivery</h2><p>Booking alerts go to {data.adminEmail}. Paid booking confirmations go to the client. {data.emailReady?'Review delivery issues here.':'Connect an email service and verified sender to enable delivery.'}</p><button className="button button-outline" disabled={busy||!data.emailReady} onClick={()=>mutate('/api/admin/emails/retry',{})}>Retry queued emails</button>{data.emails.length>0&&<ul className="email-list">{data.emails.map(e=><li key={e.id}><strong>{e.subject}</strong><span>{e.recipient} · {e.state} · {e.attempts} attempt(s)</span></li>)}</ul>}<p className="field-note">Items marked “review” need manual delivery investigation before retrying, to avoid duplicate emails.</p></section></>}
 </main></>;
}
