import { test } from 'node:test';
import assert from 'node:assert/strict';
import { database } from '../scripts/sqlite.mjs';
import { handleApi } from '../worker/api';
import { confirmVerifiedPayment } from '../worker/payments';
import { deliverEmails } from '../worker/email';
import { type Env, HOUR } from '../worker/types';
const origin='https://coach.example';
function setup(){const db=database();return{db,env:{DB:db,ADMIN_EMAIL:'coach@example.com',ALERT_EMAIL:'coach@example.com',SITE_URL:origin} as Env};}
function request(path:string,body?:unknown,admin=false,method=body?'POST':'GET',token?:string){return new Request(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(admin?{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'coach@example.com'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});}
async function slot(env:Env,start=Date.now()+48*HOUR){const input={startAt:new Date(start).toISOString(),endAt:new Date(start+HOUR).toISOString(),state:'open'};const response=await handleApi(request('/api/admin/slots',input,true),env);assert.equal(response.status,201);return{...(await response.json()),input};}
const client=(slotId:string)=>({slotId,name:'Test Player',email:'player@example.com',phone:'09171234567',players:2,location:'Test court in Manila',consent:true});
async function reserve(env:Env,id:string){const response=await handleApi(request('/api/reservations',client(id)),env);assert.equal(response.status,201);return response.json();}
async function quoted(env:Env,id:string){const r=await reserve(env,id);const response=await handleApi(request(`/api/admin/reservations/${r.id}/quote`,{totalPHP:1100},true),env);assert.equal(response.status,200);const row=await env.DB.prepare('SELECT * FROM reservations WHERE id=?').bind(r.id).first<any>();return{...r,payment:{provider:'test-provider',paymentId:crypto.randomUUID(),reservationId:r.id,quoteId:row.quote_id,amount:110000,currency:'PHP' as const,status:'paid' as const}};}
test('admin identity and mutation origin are enforced',async()=>{const{env,db}=setup();try{assert.equal((await handleApi(request('/api/admin/dashboard'),env)).status,401);const wrong=request('/api/admin/dashboard',undefined,true);wrong.headers.set('oai-authenticated-user-email','other@example.com');assert.equal((await handleApi(wrong,env)).status,403);const cross=request('/api/admin/slots',{},true);cross.headers.set('Origin','https://evil.example');assert.equal((await handleApi(cross,env)).status,403);assert.equal((await handleApi(request('/api/admin/dashboard',undefined,true),env)).status,200);}finally{db.close();}});
test('overlaps are rejected and blocked sessions never appear as available',async()=>{const{env,db}=setup();try{const s=await slot(env);assert.equal((await handleApi(request('/api/admin/slots',s.input,true),env)).status,409);assert.equal((await handleApi(request(`/api/admin/slots/${s.id}`,{...s.input,state:'blocked'},true,'PATCH'),env)).status,200);assert.equal((await handleApi(request('/api/reservations',client(s.id)),env)).status,409);}finally{db.close();}});
test('month ranges follow Manila boundaries, including last day',async()=>{const{env,db}=setup();try{const year=new Date().getUTCFullYear()+1;const end=Date.parse(`${year}-01-31T22:00:00+08:00`),next=Date.parse(`${year}-02-01T00:00:00+08:00`);db.sqlite.prepare('INSERT INTO slots VALUES (?,?,?,?)').run('jan',end,end+HOUR,'open');db.sqlite.prepare('INSERT INTO slots VALUES (?,?,?,?)').run('feb',next,next+HOUR,'open');const result=await(await handleApi(request(`/api/availability?month=${year}-01`),env)).json();assert.deepEqual(result.slots.map((s:any)=>s.id),['jan']);assert.deepEqual(Object.keys(result.slots[0]).sort(),['end_at','id','start_at']);}finally{db.close();}});
test('competing reservations produce one hold, server-calculated price and no public PII',async()=>{const{env,db}=setup();try{const s=await slot(env);const responses=await Promise.all([handleApi(request('/api/reservations',{...client(s.id),estimatedTotal:1,status:'confirmed'}),env),handleApi(request('/api/reservations',client(s.id)),env)]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,409]);const held=await responses.find(r=>r.status===201)!.json();assert.equal(held.estimatedTotal,100000);assert.equal(held.status,'pending_review');const row=db.sqlite.prepare('SELECT * FROM reservations').get() as any;assert.notEqual(row.token_hash,held.token);assert.equal((await handleApi(request(`/api/reservations/${held.id}`),env)).status,404);const status=await(await handleApi(request(`/api/reservations/${held.id}`,undefined,false,'GET',held.token),env)).json();assert.equal(status.email,undefined);assert.equal(status.phone,undefined);assert.equal((await handleApi(request(`/api/admin/slots/${s.id}`,{...s.input,state:'blocked'},true,'PATCH'),env)).status,409);}finally{db.close();}});
test('expired and cancelled holds release availability',async()=>{const{env,db}=setup();try{const s=await slot(env);const r=await reserve(env,s.id);db.sqlite.prepare('UPDATE reservations SET expires_at=? WHERE id=?').run(Date.now()-1,r.id);const second=await reserve(env,s.id);assert.equal(db.sqlite.prepare('SELECT status FROM reservations WHERE id=?').get(r.id)?.status,'expired');assert.equal((await handleApi(request(`/api/admin/reservations/${second.id}/cancel`,{},true),env)).status,200);await reserve(env,s.id);}finally{db.close();}});
test('unconfigured webhook and browser checkout cannot confirm a booking',async()=>{const{env,db}=setup();try{const s=await slot(env);const r=await quoted(env,s.id);assert.equal((await handleApi(request('/api/payments/webhook',r.payment),env)).status,503);assert.equal((await handleApi(request(`/api/reservations/${r.id}/checkout`,{},false,'POST',r.token),env)).status,503);assert.equal(db.sqlite.prepare('SELECT status FROM reservations WHERE id=?').get(r.id)?.status,'awaiting_payment');assert.equal(db.sqlite.prepare("SELECT COUNT(*) AS n FROM email_outbox WHERE id LIKE '%:confirmation'").get()?.n,0);}finally{db.close();}});
test('only matching verified payment confirms; duplicate delivery queues one confirmation',async()=>{const{env,db}=setup();try{const s=await slot(env);const r=await quoted(env,s.id);await assert.rejects(confirmVerifiedPayment(env,{...r.payment,amount:109999}));await assert.rejects(confirmVerifiedPayment(env,{...r.payment,quoteId:'tampered'}));await assert.rejects(confirmVerifiedPayment(env,{...r.payment,currency:'USD' as 'PHP'}));assert.equal((await confirmVerifiedPayment(env,r.payment)).confirmed,true);assert.equal((await confirmVerifiedPayment(env,r.payment)).duplicate,true);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM payments').get()?.n,1);assert.equal(db.sqlite.prepare("SELECT COUNT(*) AS n FROM email_outbox WHERE id LIKE '%:confirmation'").get()?.n,1);assert.equal((await handleApi(request(`/api/admin/reservations/${r.id}/cancel`,{},true),env)).status,409);}finally{db.close();}});
test('late payment cannot steal a session held by another client',async()=>{const{env,db}=setup();try{const s=await slot(env);const old=await quoted(env,s.id);db.sqlite.prepare('UPDATE reservations SET expires_at=? WHERE id=?').run(Date.now()-1,old.id);const current=await reserve(env,s.id);await assert.rejects(confirmVerifiedPayment(env,old.payment));assert.equal(db.sqlite.prepare('SELECT status FROM reservations WHERE id=?').get(current.id)?.status,'pending_review');}finally{db.close();}});
test('payment receipt cannot be reused on another reservation',async()=>{const{env,db}=setup();try{const first=await quoted(env,(await slot(env)).id);const second=await quoted(env,(await slot(env,Date.now()+72*HOUR)).id);await confirmVerifiedPayment(env,first.payment);await assert.rejects(confirmVerifiedPayment(env,{...second.payment,paymentId:first.payment.paymentId}));assert.equal(db.sqlite.prepare('SELECT status FROM reservations WHERE id=?').get(second.id)?.status,'awaiting_payment');}finally{db.close();}});
test('email waits for configuration and retry preserves idempotency without duplicates',async()=>{const{env,db}=setup();const originalFetch=globalThis.fetch;try{const r=await quoted(env,(await slot(env)).id);await confirmVerifiedPayment(env,r.payment);assert.equal((await deliverEmails(env)).connected,false);env.RESEND_API_KEY='test-not-real';env.EMAIL_FROM='Coach <coach@example.com>';const keys:string[]=[];globalThis.fetch=async(_input,init)=>{keys.push(new Headers(init?.headers).get('Idempotency-Key')!);return new Response('{}',{status:200});};assert.equal((await deliverEmails(env)).sent,2);assert.equal((await deliverEmails(env)).sent,0);assert.equal(new Set(keys).size,2);}finally{globalThis.fetch=originalFetch;db.close();}});
test('email delivery failure stays retryable and does not undo verified payment',async()=>{const{env,db}=setup();const originalFetch=globalThis.fetch;try{const r=await quoted(env,(await slot(env)).id);await confirmVerifiedPayment(env,r.payment);env.RESEND_API_KEY='test';env.EMAIL_FROM='coach@example.com';globalThis.fetch=async()=>new Response('{}',{status:503});assert.equal((await deliverEmails(env)).sent,0);assert.equal(db.sqlite.prepare('SELECT state FROM email_outbox WHERE id=?').get(`${r.id}:confirmation`)?.state,'failed');assert.equal(db.sqlite.prepare('SELECT status FROM reservations WHERE id=?').get(r.id)?.status,'confirmed');globalThis.fetch=async()=>new Response('{}',{status:200});assert.equal((await deliverEmails(env)).sent,2);}finally{globalThis.fetch=originalFetch;db.close();}});
